language: node_js

node_js:
  - node

services:
  - postgresql
  - redis-server

cache:
  yarn: true
  directories:
    - node_modules

env:
  - DATABASE_URL=psql://postgres@localhost/price_point_test

before_script:
  - psql -c 'create database price_point_test;' -U postgres
  - knex migrate:latest --env NODE_ENV

script:
  - yarn test
