language: node_js

node_js:
  - node

services:
  - postgres
  - redis-server

cache:
  yarn: true
  directories:
    - node_modules

env:

before_script:
  - psql -c 'create database thesis_test;' -U postgres

script:
  - yarn test
