language: node_js

node_js:
  - node

services:
  - postgres
  - redis-server

cache:
  yarn: true
  directories:
    - node_modules

env:
  - DATABASE_URL=postgres://postgres@localhost/travis_ci_test

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - yarn test
